title: Second Workers' Winter Olympiad 1931
title-de: Zweite Arbeiter-Wintersport-Olympiade 1931
email: k20111151@kcl.ac.uk
description: This project provides a digital archive for the 1931 Workers' Winter Olympiad that took place in Mürzzuschlag, Austria.
description-de: Dieses Projekt ist eine digitale Ausstellung für die Arbeiter-Wintersport-Olympiade 1931, die in Mürzzuschlag, Österreich, stattfand.
# >-this means to ignore newlines until "baseurl:" 
baseurl: "" # the subpath of your site, e.g. /blog
url: http://workerswinterolympiad1931.netlify.app 
# the base hostname & protocol for my site
twitter_username: ElisabethKoeni3
github_username:  Koenel
# Build settings
theme: minima
plugins:
  - jekyll-feed
include: [_pages]
collections:
  organiser:
    output: true
  organiser-de:
    output: true
  participant:
    output: true
  participant-de:
      output: true
  spectator:
    output: true
  spectator-de:
    output: true
# The next 2 steps are taken from https://www.taniarascia.com/make-a-static-website-with-jekyll/
# add Sass as css folder -  individual components will be compiled into css -- not sure if I will need this
sass:
  sass-dir: _sass